const requests = {
  fetchCreateUser: "/user/create-user",
  fetchLoginUser: "/user/login",
  fetchForgotPassword: "/auth/forgotPassword",
  fetchVerifyOtp: "/auth/verifyotp",
  fetchResetPassword: "/auth/resetPassword",
  fetchLogout: "/user/logout",
  fetchSocialLogin: "/auth/social",
  fetchAddCenter: "/center/create-center",
  fetchCategoryList: "/category/allCategory",
  fetchSearchResult: "/center/searchCenter",
  fetchImageUpload: "/image/imageUpload",
  fetchActivation: "/center/account-activation/",
  fetchCreateWorker: "/worker/create-worker",
  fetchCreateCenterSchedule: "/schedule/create-timetable",
  fetchGetWorkers: "/worker/centerWorker",
  fetchUpdateWorkers: "/worker/update-worker",
  fetchUpdateCenter: "/user/updateUser",
  fetchTimeTable: "/schedule/getTimeTable",
  fetchAddAppointment: "appointment/add-appointment",
  fetchCenter: "center/searchCenter",
  fetchCenterByDate: "schedule/getCenterByDate",
  fetchUpdateTimeTable: "/schedule/update-timetable",
  fetchPersonalService:"/service/createServicePersonal",
  fetchCollectiveService:"/service/createServiceCollective",
  fetchCenterDetails:"/center/getCenterDetail",
  fetchCenterService:"/service/findCenterService",
  fetchUpdateService:"/service/updateService",
  fetchList:"center/searchCenter",
  fetchSearchCenter: "/center/searchCenter?search=",
  fetchWorkerList: "/worker/workerList",
  fetchSearchWorker: "/worker/workerList?search=",
  fetchStatuses: "/center/userStatus",
  fetchWorkerStatus: "/worker/workerStatus",
  fetchBusiness: "/compney/allcompney",
  fetchServices: "/service/filterService ",
  fetchRates: "/plan/allPlans",
  fetchUpdatePlan: "/plan/update-plan",
  fetchAddPlan: "/plan/create-plan",
  fetchUpdateBusiness: "compney/update-compney"
}

export default requests;