const requests = {
  fetchCreateUser: "/user/create-user",
  fetchLoginUser: "/user/login",
  fetchForgotPassword: "/auth/forgotPassword",
  fetchVerifyOtp: "/auth/verifyotp",
  fetchResetPassword: "/auth/resetPassword",
  fetchSocialLogin: "/auth/social",
  fetchAddCenter: "/center/create-center",
  fetchCategoryList: "/category/allCategory",
  fetchSearchResult: "/center/searchCenter",
  fetchImageUpload: "/image/imageUpload",
  fetchActivation: "/center/account-activation/",
  fetchCreateWorker: "/worker/create-worker",
  fetchGetWorkers: "/worker/centerWorker",
  fetchCreateCenterSchedule: "/schedule/create-timetable",
  fetchUpdateWorkers: "/worker/update-worker",
  fetchCreateCenterSchedule: "/schedule/create-timetable",
  fetchUpdateCenter: "/user/updateUser",
  fetchTimeTable: "/schedule/getTimeTable",
  fetchAddAppointment: "appointment/add-appointment",
  fetchCenter: "center/searchCenter",
  fetchCenterByDate: "schedule/getCenterByDate",
  fetchUpdateTimeTable: "/schedule/update-timetable",
  fetchPersonalService:"/service/createServicePersonal",
  fetchCollectiveService:"/service/createServiceCollective",
  fetchCenterDetails:"/center/getCenterDetail",
  fetchCenterService:"/service/findCenterService",
  fetchUpdateService:"/service/updateService",
  fetchUpdateCustomSchedule:"/schedule/update-timetable",
  fetchCustomSchedule:"/schedule/getTimeTable",
  fetchWorkerDetails:"/worker/workerDetails",
  fetchWorkerServices:"service/workerServices",
  fetchUserId:"/user/find-user",
  fetchUpdateUser:"/user/updateUser",
  fetchDeleteUser:"/user/deleteUser",
  fetchEventCreate: "/event/create-event",
  fetchCenterEvents : "/event/filter-event",
  fetchWorkerData:"/worker/centerWorker",
  fetchCheckAdminPassword: "/user/checkAdmin",
  fetchCenterAdminLogin: "/user/centerAdminLogin",
  fetchSetAdminCenterPassword: "/user/set-admin-password",
  fetchCenterAdminForgotPassword: "/user/forgot-admin-password",
  fetchGetService: "/service/findCenterService/",
  fetchGetWorkersForAdmin: "/worker/centerWorker/",
  fetchGetAppomentId: "/appointment/appointmentId/",
  fetchGetAppointment: "/appointment/appointment-filter",
  fetchCenterAdminServices: "/service/findCenterService/",
  fetchCancleAppoinment:"/appointment/emergency-cancel",
  fetchWorkerLogin:"/worker/worker-login",
  fetchClientStatus:"/center/userStatus",
  fetchClientData:"/appointment/appointmentHistory",
  fetchAppoinmentData:"/appointment/appointment-detail",
  fetchCancleAppoinment:"/appointment/cancel-appointment",
  fetchUpdateAppoinment:"/appointment/update-appointment",
  
  fetchCenterAdminWorkerService:"service/workerServices",
  fetchDeleteWorkerServices:"/service/deleteServiceWorker",
  fetchActionDateWorkerHistory: "/worker/workerHistory",
  fetchDelete: "/center/delete-center",
  fetchMangeAnother: "/user/manageAnotherCenter",
  fetchUpdatePlan: "/user/createRedsysSignature",
  fetchCreatePayment: "/user/createRedsysPayment",
  fetchGetPlans: "/plan/allPlans",
  fetchDeleteWorker:'/worker/delete-worker',
  fetchSendSuggetion:"/suggestion/create-suggestion",
  fetchCreatePet:"pets/create-pets",
  fetchAllPets:"/pets/allPets",
  fetchUpdatePets:"/pets/update-pets",
  fetchAddCompany:"/compney/create-compney",
  fetchGetCompanyDetails:"/compney/center-compney",
  fetchUpdateCompany:"/compney/update-compney",

}

export default requests;