export const SET_THEME = 'SET_THEME';
export const USER_LOGIN = "USER_LOGIN";
export const SET_TOKEN = 'SET_TOKEN';
export const EMAIL = 'EMAIL';
export const REGISTER_USER = 'REGISTER_USER';
export const SET_FORGOT = 'SET_FORGOT'
export const SET_OTP = 'SET_OTP'
export const REGISTER_CENTER = 'REGISTER_CENTER'
export const DEFAULT_SCHEDULE = 'DEFAULT_SCHEDULE'
export const CUSTOM_SCHEDULE = 'CUSTOM_SCHEDULE'
export const DESTROY_SESSION = "DESTROY_SESSION"
export const WORKER_DEFAULT_SCHEDULE = "WORKER_DEFAULT_SCHEDULE"
export const WORKER_SCHEDULE = "WORKER_SCHEDULE"
export const WORKER_CUSTOM_SCHEDULE = "WORKER_CUSTOM_SCHEDULE"
export const OPEN_WORKER_MODEL = "OPEN_WORKER_MODEL"
export const WORKER_INPUT = "WORKER_INPUT"
export const SETPERSONALSERVICE = "SETPERSONALSERVICE" 
export const SETCOLLECTIVESERVICE = "SETCOLLECTIVESERVICE" 
export const COLLECTIVE_DEFAULT_SCHEDULE = "COLLECTIVE_DEFAULT_SCHEDULE"
export const COLLECTIVE_CUSTOM_SCHEDULE = "COLLECTIVE_CUSTOM_SCHEDULE"
export const OPEN_COLLECTIVESERVICE_MODEL = "OPEN_COLLECTIVESERVICE_MODEL"
export const WORKER_DATA = "WORKER_DATA"
export const CUSTOM_DATA = "CUSTOM_DATA"
export const STIME = "STIME"
export const ETIME = "ETIME"
export const DEFAULT_SCHEDULE_TIMEARRAY = "DEFAULT_SCHEDULE_TIMEARRAY"
export const DEFAULT_SCHEDULE_API_DATA = "DEFAULT_SCHEDULE_API_DATA"
export const USERID = "USERID"
export const SELECTEDCATEGORY = "SELECTEDCATEGORY"
export const SELECTED_CENTER = "SELECTED_CENTER"
export const SELECTED_ROW_DATA = "SELECTED_ROW_DATA"
export const CUSTOM_ARRAY_DATA = "CUSTOM_ARRAY_DATA"
export const CENTER_DATA = "CENTER_DATA"
export const EVENT_DATA = "EVENT_DATA"
export const EVENT_START_DATE = "EVENT_START_DATE"
export const EVENT_END_DATE = "EVENT_END_DATE"
export const SET_CENTER_ADMIN_LOGIN ="SET_CENTER_ADMIN_LOGIN"


export const CUSTOMSCHEDULETIME = "CUSTOMSCHEDULETIME"
export const MONTHEVENTS = "MONTHEVENTS"
export const SET_USER_LOGIN ="SET_USER_LOGIN"
export const APPOINTMENTDETAILS = "APPOINTMENTDETAILS"
export const OPEN_APPOINTMENT_MODEL = "OPEN_APPOINTMENT_MODEL"
export const SET_SELECTED_SERVICE_CENTER_ADMIN = "SET_SELECTED_SERVICE_CENTER_ADMIN"

export const SELECTED_WORKER_DATA = "SELECTED_WORKER_DATA"
export const CENTER_WORKER_LIST = "CENTER_WORKER_LIST"
export const WORKER_LOGIN_STATUS = "WORKER_LOGIN_STATUS"

export const WORKER_APPOINTMENT_DATA = "WORKER_APPOINTMENT_DATA"


export const SET_TAX_DATA = "SET_TAX_DATA"
export const SET_CENTER_MANAGE_ANOTHER_CENTER = "SET_CENTER_MANAGE_ANOTHER_CENTER"
export const LOGIN_DATA_ADMIN = "LOGIN_DATA_ADMIN"
export const SELECT_LANGUAGE = "SELECT_LANGUAGE"
export const SELECTED_PET = "SELECTED_PET"
export const SELECTED_LOGIN_CENTER = "SELECTED_LOGIN_CENTER"
